//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaqDiscordBot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FaqDiscordBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] quickstart {
            get {
                object obj = ResourceManager.GetObject("quickstart", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://raw.githubusercontent.com/tinf-network/faqs/main/assets/quickstart.gif.
        /// </summary>
        internal static string UnansweredQuestionInstructionsImage_Url {
            get {
                return ResourceManager.GetString("UnansweredQuestionInstructionsImage_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stelle deine Frage auf dem TINF Network Server und antworte auf deine Nachricht hier sobald du eine Antwort hast, um sie in die Wissensdatenbank aufzunehmen.
        ///
        ///Unsicher? Antworte mit `tutorial` um eine Anleitung zu erhalten..
        /// </summary>
        internal static string UnansweredQuestionInstructionsText_Desc_Pro {
            get {
                return ResourceManager.GetString("UnansweredQuestionInstructionsText_Desc_Pro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hilfe dabei, deine Frage in die Wissensdatenbank aufzunehmen.
        ///
        ///**Und so geht es**:
        ///**1.** Stelle deine Frage auf dem TINF Network Server (bspw. im #dhbw-overflow Kanal).
        ///**2.** Sobald du eine Antwort erhalten hast, antworte hier auf deine Ursprungsnachricht (siehe GIF) in möglichst ausführlicher Fassung.
        ///**3.** Deine Antwort wird überprüft und anschließend in die Wissensdatenbank aufgenommen, sodass sie anderen Studierenden zur Verfügung steht.
        ///
        ///Melde dich beim Orga-Team, falls du Schwierigkeiten dab [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UnansweredQuestionInstructionsText_Desc_Rookie {
            get {
                return ResourceManager.GetString("UnansweredQuestionInstructionsText_Desc_Rookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kannst innerhalb von {0} deine Antwort beisteuern..
        /// </summary>
        internal static string UnansweredQuestionInstructionsText_Footnote {
            get {
                return ResourceManager.GetString("UnansweredQuestionInstructionsText_Footnote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ich konnte keine Antwort finden.
        /// </summary>
        internal static string UnansweredQuestionInstructionsText_Title_Pro {
            get {
                return ResourceManager.GetString("UnansweredQuestionInstructionsText_Title_Pro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ich konnte keine Antwort finden. Du kannst trotzdem fündig werden:.
        /// </summary>
        internal static string UnansweredQuestionInstructionsText_Title_Rookie {
            get {
                return ResourceManager.GetString("UnansweredQuestionInstructionsText_Title_Rookie", resourceCulture);
            }
        }
    }
}
